#!/usr/bin/env bash

set -e

declare -a dotfiles=(
    ".bashrc.d/00_home_bin"
    ".bashrc.d/mpv"
    ".bashrc.d/oci"
    ".bashrc.d/starship"
    ".bashrc.d/tmp"
    ".bashrc.d/nvim"
    ".bashrc.d/vscode"
    ".config/clangd/config.yaml"
    ".config/gdb/gdbinit"
    ".config/glirc/config"
    ".config/nvim/init.lua"
    ".config/nvim/lua/include/colors.lua"
    ".config/nvim/lua/include/colorscheme.lua"
    ".config/nvim/lua/include/paq_spec.lua"
    ".config/nvim/lua/include/paths.lua"
    ".config/nvim/lua/include/strings.lua"
    ".config/nvim/lua/include/terminals.lua"
    ".config/nvim/lua/plugin_config/init.lua"
    ".config/nvim/lua/plugin_config/leap.lua"
    ".config/nvim/lua/plugin_config/lsp.lua"
    ".config/nvim/lua/plugin_config/lualine.lua"
    ".config/nvim/lua/plugin_config/nvim-tree.lua"
    ".config/nvim/lua/plugin_config/telescope.lua"
    ".config/nvim/lua/plugin_config/treesitter.lua"
    ".config/nvim/lua/scripts/execute_current_file.lua"
    ".config/nvim/lua/scripts/general_terminal.lua"
    ".config/nvim/lua/scripts/help_no_split.lua"
    ".config/nvim/lua/scripts/init.lua"
    ".config/nvim/lua/scripts/per_directory.lua"
    ".config/nvim/lua/scripts/read_into_tabnew.lua"
    ".config/nvim/lua/scripts/read_into_vnew.lua"
    ".config/nvim/lua/scripts/terminal_vnew.lua"
    ".config/starship.toml"
    ".gitconfig"
    ".var/app/io.mpv.Mpv/config/mpv/mpv.conf"
    ".var/app/org.wezfurlong.wezterm/config/wezterm/${HOSTNAME}_wezterm.lua"
)

base_src_dir="src"
base_dest_dir="$HOME"

for dotfile in "${dotfiles[@]}"; do
    dotfile_src_path="$base_src_dir/$dotfile"
    dotfile_dest_path="$base_dest_dir/$dotfile"

    if [[ ! -f "$dotfile_src_path" ]]; then
        echo "warning: $dotfile_src_path not found"
        continue
    fi

    dotfile_dest_dir="$(dirname "$dotfile_dest_path")"
    mkdir -p "$dotfile_dest_dir"

    file_mode="0444"
    if [[ -x "$dotfile_src_path" ]]; then
        file_mode="0555"
    fi

    install -C -m "$file_mode" -T "$dotfile_src_path" "${dotfile_dest_path/${HOSTNAME}_/}"
done

# install/clean nvim plugins
nvim --headless -u NONE -c "luafile $HOME/.config/nvim/lua/include/paq_spec.lua" -c PaqClean -c PaqInstall -c qa
printf "\n"
