#!/usr/bin/env bash

set -e

declare -a dotfiles=(
    ".bashrc.d/00_home_bin"
    ".bashrc.d/mpv"
    ".bashrc.d/starship"
    ".bashrc.d/tmp"
    ".bashrc.d/nvim"
    ".bashrc.d/vscode"
    ".config/nvim/init.lua"
    ".config/nvim/lua/plugins/telescope.lua"
    ".config/nvim/lua/plugins/treesitter.lua"
    ".config/nvim/lua/plugins/vscode.lua"
    ".config/nvim/lua/scripts/init.lua"
    ".config/nvim/lua/scripts/read_into_vnew.lua"
    ".config/starship.toml"
    ".gitconfig"
    ".var/app/io.mpv.Mpv/config/mpv/mpv.conf"
    ".var/app/org.wezfurlong.wezterm/config/wezterm/${HOSTNAME}_wezterm.lua"
)

base_src_dir="src"
base_dest_dir="$HOME"

for dotfile in "${dotfiles[@]}"; do
    dotfile_src_path="$base_src_dir/$dotfile"
    dotfile_dest_path="$base_dest_dir/$dotfile"
    dotfile_dest_dir="$(dirname "$dotfile_dest_path")"
    mkdir -p "$dotfile_dest_dir"
    install -C -m 0444 -T "$dotfile_src_path" "${dotfile_dest_path/${HOSTNAME}_/}"
done
