-- Color palette that extends the default theme.
-- This palette was generated by paletton based on NvimLightCyan (#8cf8f7).
-- Paletton settings: adjacent colors (with complementary), hue 210, dist 30.

return {
    light_cyan = "#c0fdfd",
    cyan = "NvimLightCyan",
    dark_cyan = "#61efef",
    darker_cyan = "#3bdddd",
    light_green = "#c1fec1",
    green = "#8efb8e",
    dark_green = "#64f764",
    darker_green = "#3fee3f",
    light_lavender = "#c6d7fd",
    lavender = "#98b5f9",
    dark_lavender = "#7198f2",
    darker_lavender = "#4e7be3",
    light_orange = "#ffddc1",
    orange = "#ffc290",
    dark_orange = "#ffac67",
    darker_orange = "#ff9843",
    dark_grey = "NvimDarkGrey3",
    light_grey = "NvimLightGrey2",
}
