require("scripts.cmake_keybindings")
require("scripts.execute_current_file")
require("scripts.general_terminal")
require("scripts.per_directory")
require("scripts.read_into_vnew")
require("scripts.terminal_vnew")
