require("scripts.execute_current_file")
require("scripts.general_terminal")
require("scripts.help_no_split")
require("scripts.per_directory")
require("scripts.project_terminals")
require("scripts.read_into_tabnew")
require("scripts.read_into_vnew")
require("scripts.terminal_vnew")
