format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$container\
$hostname\
$line_break\
$jobs\
$shlvl\
$character"""

add_newline = false

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold green)'

[container]
format = "[\n\\[$name\\]]($style)"
style = 'bold green'

[directory]
truncation_length = 100
truncate_to_repo = true

[git_branch]
format = '[$branch(:$remote_branch)]($style) '

[git_status]
ahead = '+'
behind = '-'
diverged = '+-'
staged = '&'
renamed = 'r'
deleted = 'd'

[hostname]
ssh_symbol = '@'
trim_at = ''
format = "[\n$ssh_symbol$hostname]($style)"
style = "bold blue"

[jobs]
symbol_threshold = 1
number_threshold = 1
symbol = '+'

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = '>'
# threshold should be 2 and repeat_offset should be 1, but there's a bug with the shlvl handling in bash.
threshold = 1
repeat_offset = 0
style = 'bold green'
