# keybindings for "tab" handling
set -s user-keys[0] "\e[1;6T"
bind-key -n User0 new-window
bind-key -n C-PPage previous-window
bind-key -n C-NPage next-window

# style shit
set -g status-position top
set -g status-style bg=default,fg=white
set -g status-right ""
set -g status-interval 1
set-window-option -g window-status-format " #W "
set-window-option -g window-status-style bg=default,fg=darkgrey
set-window-option -g window-status-current-format " #W "
set-window-option -g window-status-current-style bg=darkgrey,fg=black
