local configs = require("nvim-treesitter.configs")
configs.setup({
    ensure_installed = {
        "bash",
        "c",
        "clojure",
        "cmake",
        "commonlisp",
        "cpp",
        "dart",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitignore",
        "java",
        "javascript",
        "json",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "python",
        "racket",
        "scheme",
        "ssh_config",
        "typescript",
        "vim",
        "vimdoc",
    },
    sync_install = false,
    highlight = { enable = true },
})
